### PR TITLE
Fix #29: Make maxStackSize configurable

### LINKED ISSUE #29: Allow MAX_STACK_SIZE to be configured in NewRelicEncoder
The NewRelicEncoder for logback uses the NewRelicJsonLayout to encode stack traces in log messages.

The layout has a hardcoded stack size of 10 lines, which is way too small for Groovy programs which produce large amounts of fluff in their stacks.

It would be ideal if the encoder could take the maxStackSize as a parameter when creating it:

```
 encoder(com.newrelic.logging.logback.NewRelicEncoder) {
    maxStackSize = 50
}
```

It might also be useful to be able to add a stack trace filter of some kind, maybe a Regex expression that could be matched as an exclusion for stack trace lines.

### PR DESCRIPTION
**Pull request by longwa**
Allows configuring the maxStackSize on the `NewRelicEncoder` for logback.

### CODE REVIEW

**Comment by jeffalder** [comment]
This is great, thanks for the contribution! Is this settable via XML as-is? If not, what would it take?

File: logback/src/main/java/com/newrelic/logging/logback/NewRelicJsonLayout.java [hunk 1]
```diff
@@ -23,6 +23,16 @@
 import static com.newrelic.logging.core.ExceptionUtil.MAX_STACK_SIZE;
 
 public class NewRelicJsonLayout extends LayoutBase<ILoggingEvent> {
+    private Integer maxStackSize;
```
Comment (breedx-nr) [inline logback/src/main/java/com/newrelic/logging/logback/NewRelicJsonLayout.java:26]: Can we make this `final`?

File: core/src/main/java/com/newrelic/logging/core/ExceptionUtil.java [hunk 2]
```diff
@@ -17,12 +17,16 @@ public static String getErrorStack(Throwable throwable) {
...
+    }
+
+    public static String getErrorStack(StackTraceElement[] stack, Integer maxStackSize) {
         if (stack == null || stack.length == 0) {
             return null;
         }
 
-        StringBuilder stackBuilder = new StringBuilder();
-        for(int i = 0; i < Math.min(MAX_STACK_SIZE, stack.length); i++) {
+        StringBuilder stackBuilder = new StringBuilder(maxStackSize);
```
Comment (breedx-nr) [inline core/src/main/java/com/newrelic/logging/core/ExceptionUtil.java:28]: I don't think that `maxStackSize` is a good choice for the `StringBuilder` initial capacity.  Would prefer to leave that out or set it to something more reasonable (maybe 4k is a better guess?).

File: logback/src/main/java/com/newrelic/logging/logback/NewRelicEncoder.java [hunk 3]
```diff
@@ -28,7 +30,9 @@
  * @see <a href="https://logback.qos.ch/manual/encoders.html#interface">Logback Encoders</a>
  */
 public class NewRelicEncoder extends EncoderBase<ILoggingEvent> {
-    private NewRelicJsonLayout layout = new NewRelicJsonLayout();
+    private NewRelicJsonLayout layout;
+
+    Integer maxStackSize = MAX_STACK_SIZE;
```
Comment (breedx-nr) [inline logback/src/main/java/com/newrelic/logging/logback/NewRelicEncoder.java:35]: How does this get changed?

**Review by breedx-nr — CHANGES_REQUESTED** [review]
Thanks for the submission!  This is a great idea.
Overall, it does look good, but I did have a few small suggestions and a question.

File: core/src/main/java/com/newrelic/logging/core/ExceptionUtil.java (hunk 2 above)
Comment (longwa) [reply core/src/main/java/com/newrelic/logging/core/ExceptionUtil.java:28]: Oops, yeah sorry, I was thinking about that from a number of lines perspective, not a strength length perspective. I'll remove it.

File: logback/src/main/java/com/newrelic/logging/logback/NewRelicEncoder.java (hunk 3 above)
Comment (longwa) [reply logback/src/main/java/com/newrelic/logging/logback/NewRelicEncoder.java:35]: I've been using Groovy too long. I'll add a setter for everyone else.

File: logback/src/main/java/com/newrelic/logging/logback/NewRelicJsonLayout.java (hunk 1 above)
Comment (longwa) [reply logback/src/main/java/com/newrelic/logging/logback/NewRelicJsonLayout.java:26]: > This is great, thanks for the contribution! Is this settable via XML as-is? If not, what would it take?

I'll create a Java project using XML syntax and see what it would take. Should be pretty easy.

**Comment by longwa** [comment]
> This is great, thanks for the contribution! Is this settable via XML as-is? If not, what would it take?

I'll create a simple test project in Java using XML and test it shortly. Thanks for considering the change.

File: logback/src/main/java/com/newrelic/logging/logback/NewRelicJsonLayout.java (hunk 1 above)
Comment (longwa) [reply logback/src/main/java/com/newrelic/logging/logback/NewRelicJsonLayout.java:26]: For sure.

**Review by breedx-nr — APPROVED** [review]
Thanks for the help!

**Comment by cortexcompiler** [comment]
Does this mean that the README could be updated to show that this is supported? :
```
        <encoder class="com.newrelic.logging.logback.NewRelicEncoder">
        	<max-stack-size>50</max-stack-size>
        </encoder>
```
